
"smart_sources:Хранилище/-/Языки программирования/Python/Питон/Лекция 6 Питон.md": {"path":"Хранилище/-/Языки программирования/Python/Питон/Лекция 6 Питон.md","last_embed":{"hash":null},"embeddings":{},"last_read":{"hash":"1ocw23i","at":1760991546241},"class_name":"SmartSource","last_import":{"mtime":1760991534645,"size":16247,"at":1760991546246,"hash":"1ocw23i"},"blocks":{"#Phython":[1,1],"#Исключения и работа с ошибками":[2,377],"#Исключения и работа с ошибками##Подробное руководство по исключениям и обработке ошибок в Python":[3,203],"#Исключения и работа с ошибками##Подробное руководство по исключениям и обработке ошибок в Python#1. Основы исключений":[5,30],"#Исключения и работа с ошибками##Подробное руководство по исключениям и обработке ошибок в Python#1. Основы исключений#{1}":[6,30],"#Исключения и работа с ошибками##Подробное руководство по исключениям и обработке ошибок в Python#2. Обработка исключений: try/except":[31,55],"#Исключения и работа с ошибками##Подробное руководство по исключениям и обработке ошибок в Python#2. Обработка исключений: try/except#{1}":[32,55],"#Исключения и работа с ошибками##Подробное руководство по исключениям и обработке ошибок в Python#3. Генерация исключений: оператор `raise`":[56,72],"#Исключения и работа с ошибками##Подробное руководство по исключениям и обработке ошибок в Python#3. Генерация исключений: оператор `raise`#{1}":[57,72],"#Исключения и работа с ошибками##Подробное руководство по исключениям и обработке ошибок в Python#4. Пользовательские исключения":[73,97],"#Исключения и работа с ошибками##Подробное руководство по исключениям и обработке ошибок в Python#4. Пользовательские исключения#{1}":[74,97],"#Исключения и работа с ошибками##Подробное руководство по исключениям и обработке ошибок в Python#5. Цепочки исключений (Exception Chaining)":[98,113],"#Исключения и работа с ошибками##Подробное руководство по исключениям и обработке ошибок в Python#5. Цепочки исключений (Exception Chaining)#{1}":[99,113],"#Исключения и работа с ошибками##Подробное руководство по исключениям и обработке ошибок в Python#6. Трассировка стека (Stack Trace)":[114,131],"#Исключения и работа с ошибками##Подробное руководство по исключениям и обработке ошибок в Python#6. Трассировка стека (Stack Trace)#{1}":[115,131],"#Исключения и работа с ошибками##Подробное руководство по исключениям и обработке ошибок в Python#7. Ассерты (Assertions)":[132,144],"#Исключения и работа с ошибками##Подробное руководство по исключениям и обработке ошибок в Python#7. Ассерты (Assertions)#{1}":[133,144],"#Исключения и работа с ошибками##Подробное руководство по исключениям и обработке ошибок в Python#8. Контекстные менеджеры и исключения":[145,176],"#Исключения и работа с ошибками##Подробное руководство по исключениям и обработке ошибок в Python#8. Контекстные менеджеры и исключения#{1}":[146,176],"#Исключения и работа с ошибками##Подробное руководство по исключениям и обработке ошибок в Python#9. Логирование исключений":[177,203],"#Исключения и работа с ошибками##Подробное руководство по исключениям и обработке ошибок в Python#9. Логирование исключений#{1}":[178,203],"#Исключения и работа с ошибками##Домашнее задание (10 заданий)":[204,248],"#Исключения и работа с ошибками##Домашнее задание (10 заданий)#{1}":[206,248],"#Исключения и работа с ошибками##Ресурсы для изучения":[249,255],"#Исключения и работа с ошибками##Ресурсы для изучения#{1}":[250,255],"#Исключения и работа с ошибками##Пример решения задачи 1 (Безопасный калькулятор)":[256,303],"#Исключения и работа с ошибками##Пример решения задачи 1 (Безопасный калькулятор)#{1}":[257,303],"#Исключения и работа с ошибками##Пример решения задачи 7 (Транслятор ошибок)":[304,335],"#Исключения и работа с ошибками##Пример решения задачи 7 (Транслятор ошибок)#{1}":[305,335],"#Исключения и работа с ошибками##Пример решения задачи 10 (Агрегирование ошибок)":[336,377],"#Исключения и работа с ошибками##Пример решения задачи 10 (Агрегирование ошибок)#{1}":[337,377]},"outlinks":[{"title":"Официальная документация: исключения","target":"https://docs.python.org/3/tutorial/errors.html","line":250},{"title":"Built-in Exceptions","target":"https://docs.python.org/3/library/exceptions.html","line":251},{"title":"Python Exception Handling","target":"https://realpython.com/python-exceptions/","line":252},{"title":"Logging HOWTO","target":"https://docs.python.org/3/howto/logging.html","line":253},{"title":"Context Managers","target":"https://realpython.com/python-with-statement/","line":254}],"metadata":{"tags":["#Phython"]},"task_lines":[]},